# Generated by Django 2.0.2 on 2018-02-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collector', '0002_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.TextField(unique=True),
        ),
    ]
