name: Build and deploy
on: [push, pull_request]

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCS_PROJECT }}
          service_account_key: ${{ secrets.GCS_SA_KEY }}
          export_default_credentials: true
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        run: |-
          gcloud app deploy
